### ISSUE TITLE
Access applications and databases via GUI

### ISSUE THREAD

**Issue by meniem** [bastillion-io/Bastillion-EC2#67]
Hello all,

Is it possible to access the private AWS databases through any UI; such as MySQL Workbench.

Because currently we can access the bastion from the Bastillion web console, and from it we access other private instances via the terminal only. 

We need to know if we can implement any SSH tunneling to open our applications and databases via GUI.

Thanks,
Ali

**Comment by skavanagh** [comment]
SSH tunneling will not work through bastillion. You will have to use a traditional SSH client to forward ports or tunnel.

**Comment by meniem** [comment]
Thanks Sean for your reply. 

We're linking the DB instance with the key pair of "Bastillion", and they are in private subnets. So, how the traditional SSH client would work in that case.

**Comment by skavanagh** [comment]
A tradition SSH client wouldn't, if its not allowed.  There was a topic on this on reddit the other day.

https://www.reddit.com/r/aws/comments/bbqfxd/how_to_connect_to_instances_via_a_gui_without/

and one of the answers was to setup a server with guacamole - https://guacamole.apache.org/

**Comment by meniem** [comment]
Thanks Sean, really appreciated.
